State action
UBC-Rocket/Sky-Pilot pull request #148
Opened 2021-02-05 04:45 UTC by jesseli2002

https://trello.com/c/xLl7nl9E/91-review-state-machine-states-and-add-actual-event-functions-eg-deploydrogue-where-applicable

2021-02-05 05:03 UTC, SilentSys requested changes

2021-02-05 05:03 UTC, SilentSys commented on avionics/common/include/hardware/ignitor.h
> -#pragma once
Why? What's wrong with `#pragma once`?

2021-02-05 05:03 UTC, SilentSys commented on t
> +[1mdiff --git a/avionics/common/include/states/landed.h b/avionics/common/include/states/landed.h[m
??

2021-02-06 20:50 UTC, jesseli2002 commented on avionics/common/include/hardware/ignitor.h
> -#pragma once
Technically it's not standard-compliant, and also it makes it possible to override the contents of the file in tests

2021-02-06 20:51 UTC, jesseli2002 commented on t
> +[1mdiff --git a/avionics/common/include/states/landed.h b/avionics/common/include/states/landed.h[m
yeah i've no idea what happened there, probably a few terminal commands gone wrong

2021-02-10 03:14 UTC, akoen approved these changes

2021-02-10 06:50 UTC, SilentSys approved these changes

2021-02-10 06:50 UTC, merged