Implement voltage sensor
UBC-Rocket/Sky-Pilot pull request #168
Opened 2021-07-10 07:05 UTC by jordans6

Uses old battery.cpp and battery.h files to implement battery as a sensor

2021-07-11 19:01 UTC, jesseli2002 requested changes
Looks like battery voltage sensor has the unique property that it can be implemented entirely through already-provided hardware abstractions - no need to put separate code under `envs/board` and `envs/x86`. I don't think there's any actual code changes - just moving around of some files: 
- Delete old battery.h and battery.cpp files
- Move board/src/sensors/battery.cpp to common/src/sensors/battery.cpp
- Move board/include/sensors/battery_sensor.h to common/include/sensors/battery.hpp

2021-07-11 19:01 UTC, jesseli2002 commented on avionics/envs/board/src/sensors/battery.cpp
> +}
It's probably better practice to leave a newline at the end of each file - check your IDE to see if there's an option to automatically add a newline (and not render it); e.g. VS Code has Render Final Newline & Insert Final Newline options

2021-07-12 04:16 UTC, jordans6 commented on avionics/envs/board/src/sensors/battery.cpp
> +}
Adjusted that setting now - 7eeedd5

2021-07-12 04:17 UTC, jordans6 commented
> Looks like battery voltage sensor has the unique property that it can be implemented entirely through already-provided hardware abstractions - no need to put separate code under `envs/board` and `envs/x86`. I don't think there's any actual code changes - just moving around of some files:
> 
> * Delete old battery.h and battery.cpp files
> * Move board/src/sensors/battery.cpp to common/src/sensors/battery.cpp
> * Move board/include/sensors/battery_sensor.h to common/include/sensors/battery.hpp

Made those changes
7eeedd5

2021-07-12 04:28 UTC, jesseli2002 approved these changes
LGTM

2021-07-12 04:28 UTC, merged